name: build

on:
  push:
    branches:
      - master
      - beta

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set tag to beta
        if: endsWith(github.ref, '/beta')
        run: |
          echo "::set-env name=TAG::beta"
          echo "::set-env name=DOCKERFILE::Dockerfile.beta"
      -
        name: Set tag to latest
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=TAG::latest"
          echo "::set-env name=DOCKERFILE::Dockerfile"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            --tag jakowenko/route53-dynamic-dns:${TAG} \
            --file ./docker/${DOCKERFILE} .
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag jakowenko/route53-dynamic-dns:${TAG} \
            --file ./docker/${DOCKERFILE} .
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery jakowenko/route53-dynamic-dns:${TAG}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json